client: "127.0.0.1:0"

server: "127.0.0.1:8888"

dns_use_system_defaults: true

delay: "5s"

jitter: 50

protocol: "dns"

tls_key: "./certs/server.key"
tls_cert: "./certs/server.crt"

path_to_request: "./configs/request.yaml"
path_to_response: "./configs/response.yaml"